### ISSUE TITLE
App Crash in Info Hub 

### ISSUE THREAD

**Issue by codingblazer** [systers/malaria-app-android#180]
If we press Effective Against Malaria in Info hub and while its loading, orientation is changed, the app crashes sometimes. The logcat is given below -

```
java.lang.IllegalArgumentException: View=com.android.internal.policy.PhoneWindow$DecorView{3dfb00e V.E...... R......D 0,0-1368,336} not attached to window manager
                                                                         at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:424)
                                                                          at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:350)
                                                                          at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
                                                                          at android.app.Dialog.dismissDialog(Dialog.java:362)
                                                                          at android.app.Dialog.dismiss(Dialog.java:345)
                                                                          at com.peacecorps.malaria.activities.EffectivenessFragmentActivity.hidepDialog(EffectivenessFragmentActivity.java:172)
```
<img src="https://cloud.githubusercontent.com/assets/13872065/21748825/18588230-d5b5-11e6-8dcb-8c8ced632e60.gif" height="400" width="200">

@yatna @chhavip Should I send PR ?

**Comment by yatna** [comment]
@codingblazer We are currently holding any orientation change related issue.

**Comment by geekanamika** [comment]
info-hub is not implemented in updated code, we can open this issue later.
