### ISSUE TITLE
App crashes in MedicineStore Activity

### ISSUE THREAD

**Issue by HimanshuS01** [systers/malaria-app-android#197]
**Current Behaviour**
If the user enters any big number in **Add medicine to store** dialog then app crashes .

![ezgif com-optimize 3](https://cloud.githubusercontent.com/assets/18090596/21898516/145ae0f4-d913-11e6-8956-5f547bb56c60.gif)

**Logcat for the issue**
01-12 19:59:58.141 4508-4508/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.peacecorps.malaria, PID: 4508
                                                 java.lang.NumberFormatException: Invalid int: "744644464643377976767"
                                                     at java.lang.Integer.invalidInt(Integer.java:138)
                                                     at java.lang.Integer.parse(Integer.java:413)                                                 
                                                     at java.lang.Integer.parseInt(Integer.java:334)
                                                     at com.peacecorps.malaria.activities.MedicineStore$2$1.onClick(MedicineStore.java:167)
                                                     at android.view.View.performClick(View.java:5201)                                         
                                                     at android.os.Handler.handleCallback(Handler.java:746)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                     at java.lang.reflect.Method.invoke(Native Method)
     
**Expected behaviour**
Either we can introduce a check on this value so that user will be shown an error message if he crosses that particular limit  **or**
we can restrict the user to type the value upto a certain limit.

@chhavip @yatna I would like to ask,what approach should I follow either first--> to introduce a check or second -->to type value upto certain limit.

After the approval I will send the PR.Thanks :)

**Comment by chhavip** [comment]
Display a warning in case user crosses an appropriate limit or this can even be implemented as a drop down of values.

**Comment by HimanshuS01** [comment]
Sure @chhavip and I would like to ask what limit should I set  while entering the value ?

**Comment by anubhakushwaha** [comment]
Closing.Fixed via #219
