### ISSUE TITLE
Settings Clear Dialog Causing Window Leak error

### ISSUE THREAD

**Issue by sammy1997** [systers/malaria-app-android#274]
What is wrong?
The Dialog to clear the cache is causing a Window Leak Error

Steps to reproduce the issue.

Go to HomeScreenFragment, press on the settings button, then yes. Follow the logcat.

Expected behaviour :
Error is probably being caused becuse Dialog lifetime is exceeding Fragment Lifetime, which shouldn't have happened.

Development environment
1. Device model - Nexus-5 (Emulator)
2. Android version - API 24

LogCat :

 11-14 00:42:38.392 2417-2417/com.peacecorps.malaria E/WindowManager: android.view.WindowLeaked: Activity com.peacecorps.malaria.activities.MainActivity has leaked window DecorView@c6b7ffd[Reset Data] that was originally added here
                                                                         at android.view.ViewRootImpl.<init>(ViewRootImpl.java:417)
                                                                         at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
                                                                         at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
                                                                         at android.app.Dialog.show(Dialog.java:316)
                                                                         at com.peacecorps.malaria.fragment.HomeScreenFragment.addDialog(HomeScreenFragment.java:529)
                                                                         at com.peacecorps.malaria.fragment.HomeScreenFragment$1.onClick(HomeScreenFragment.java:102)
                                                                         at android.view.View.performClick(View.java:5610)
                                                                         at android.view.View$PerformClick.run(View.java:22265)
                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at 
android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

Do I want to work on the issue?
If assigned, then yes.

@anubhakushwaha  Please review this issue once

**Comment by anubhakushwaha** [comment]
@sammy1997 How do you propose to solve it?

**Comment by sammy1997** [comment]
@anubhakushwaha  a simple solution is to add the following lines to all the fragments that have the settings button and are creating a dialog :

@Override public void onStop() { 
               if (dialog != null) {
                            dialog.dismiss(); 
                            dialog = null; 
               }
              super.onStop();
 }

This will prevent the dialog from existing after the activity gets over.
Agreed ?

**Comment by anubhakushwaha** [comment]
@sammy1997  Yes go ahead, along with this please look for other sources of memory leak if any. Thanks.

**Comment by DipanshKhandelwal** [comment]
Since no one has worked on it from so long, can I solve it ?

**Comment by geekanamika** [comment]
@DipanshKhandelwal Go ahead.

**Comment by DipanshKhandelwal** [comment]
OK will send a PR soon :+1:
